# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9cd4ce18909a9c7922414aef46502f275e7eb92873adfe6f7221abe09140e164dd2117c35a235cd7673d9f07b31f5ea5beb9b28a9269ad04c508ad71fcdc91

test:
  secret_key_base: 3c8850f6888d7a3fa98452131e3fd536ae3e587ce59541d5adaf2261894abee2792c2a19b83707cd520b11e2b32593a7ff7b4bfad7352a876731b729d68f1025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
